FROM node:latest

# instruction tells Docker how to test a container to check that it is still working.
HEALTHCHECK --interval=5s \
            --timeout=5s \
            CMD curl -f http://localhost:8000 || exit 1

EXPOSE 8000